### ISSUE TITLE
Armips Usage

### ISSUE THREAD

**Issue by Normmatt** [kcaze/magical_vacation_translation#1]
Have you guys seen https://github.com/Kingcom/armips its an assembler designed for rom hacking in mind it lets you assemble code directly into the rom without having to manually copy and paste it via a hex editor. 

If you need some examples of how to use it you can see how I use it in my GBA projects.

**Comment by kcaze** [comment]
I'm new to ROM hacking so no I haven't actually. I've been using Goldroad assembler so far but I'll look into switching to armips. Thanks for the recommendation!
